apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
    name: elasticsearch
    targetPort: 9200
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: elasticsearch
subsets:
- addresses:
  - ip: 192.168.10.100
  ports:
   - port: 9200
     name: elasticsearch