apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argorollout-blue-green
    repoURL: 'http://gitlab.cuiliangblog.cn/devops/argo-demo.git'
    targetRevision: main
  sources: []
  project: devops
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
