apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: thanos-compact
  namespace: thanos
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`thanos-compact.cuiliangblog.cn`)
    kind: Rule
    services:
    - name: thanos-compact
      port: 10902   