apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: thanos-ruler
  namespace: monitoring
spec:
  entryPoints:
  - web
  routes:
    - match: Host(`thanos-ruler.cuiliangblog.cn`)
      kind: Rule
      services:
        - name: thanos-ruler-operated
          port: 10902