apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: opentelemetry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry.center
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry
  ports:
  - port: 4318
    targetPort: 4318
