kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-thanos-compact-0
  namespace: thanos
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi