apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: database-compactor
    app.kubernetes.io/instance: thanos-compact
    app.kubernetes.io/name: thanos-compact
    app.kubernetes.io/version: v0.30.2
  name: thanos-compact
  namespace: thanos
spec:
  endpoints:
  - port: http
    relabelings:
    - action: replace
      separator: /
      sourceLabels:
      - namespace
      - pod
      targetLabel: instance
    - action: replace
      regex: shard\-(\d+)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_service_label_compact_thanos_io_shard
      targetLabel: shard
  selector:
    matchLabels:
      app.kubernetes.io/component: database-compactor
      app.kubernetes.io/name: thanos-compact
