apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https-middleware
  namespace: argo-rollouts
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  entryPoints:
    - web
    - websecure 
  tls:
    secretName: ingress-tls                
  routes:
  - match: Host(`argo-rollouts.cuiliangblog.cn`)
    kind: Rule
    services:
    - name: argo-rollouts-dashboard
      port: 3100
    middlewares:
    - name: redirect-https-middleware