apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https-middleware
  namespace: observability
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: observability
  namespace: observability 
spec:
  entryPoints:
  - web
  - websecure 
  tls:
    secretName: ingress-tls
  routes:
  - match: Host(`watchalert.cuiliangblog.cn`) # 域名
    kind: Rule
    services:
      - name: watchalert-web   # 与svc的name一致
        port: 80    # 与svc的port一致  
    middlewares:
      - name: redirect-https-middleware 