kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-thanos-receive-ingestor-default-0
  namespace: thanos
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-thanos-receive-ingestor-default-1
  namespace: thanos
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi