apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: rabbitmq-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 30005