apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
spec:
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
      annotations:
        instrumentation.opentelemetry.io/inject-java: "opentelemetry/java-instrumentation" # 填写 Instrumentation 资源的名称
        sidecar.opentelemetry.io/inject: "opentelemetry/sidecar" # 注入一个 sidecar 模式的 OpenTelemetry Collector
    spec:
      containers:
      - name: java-demo
        image: contrastsecuritydemo/spring-petclinic:1.5.1
        # image: harbor.cuiliangblog.cn/otel/spring-petclinic:1.5.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-demo
spec:
  selector:
    app: java-demo
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: java-demo
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`java-demo.cuiliangblog.cn`)
    kind: Rule
    services:
      - name: java-demo
        port: 8080