kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  storageClassName: ceph-cephfs # StorageClass名称
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
