apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root      # 应用名称，可自定义
  namespace: argocd           # 注意：Application 必须部署在 argocd 命名空间
spec:
  project: devops
  source:
    repoURL: http://gitlab.cuiliangblog.cn/devops/gitops-applicationSet.git
    path: applications
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:                               # 启用自动同步
      prune: true                            # 自动删除 Git 中已移除的资源
      selfHeal: true                         # 自动修复偏离集群状态的资源