FROM node:16.15.0 AS build
COPY vue3_vite_element-plus /vue
WORKDIR /vue
RUN npm install --registry https://registry.npm.taobao.org && npm run build

FROM nginx:1.20.1
COPY --from=build /vue/dist /opt/vue/dist
COPY vue3_vite_element-plus/vue.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g","daemon off;"]
