annotations:
  category: Analytics
  images: |
    - name: kibana
      image: docker.io/bitnami/kibana:8.12.2-debian-12-r0
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r16
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.12.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Kibana is an open source, browser based analytics and search dashboard for Elasticsearch. Kibana strives to be easy to get started with, while also being flexible and powerful.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/kibana/img/kibana-stack-220x234.png
keywords:
- kibana
- analytics
- monitoring
- metrics
- logs
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: kibana
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kibana
version: 10.13.0
