apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
      - name: nginx-exporter
        image: harbor.local.com/library/nginx/nginx-prometheus-exporter:latest
        args:
        - "-nginx.scrape-uri=http://nginx/stub_status"
        ports:
        - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: default
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113
