apiVersion: v2
appVersion: 4.1.2
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.4.4
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.9.4
description: Apache Superset is a modern, enterprise-ready business intelligence web
  application
home: https://superset.apache.org/
icon: https://artifacthub.io/image/68c1d717-0e97-491f-b046-754e46f46922@2x
keywords:
- business intelligence
- data science
maintainers:
- email: craig@craigrueda.com
  name: craig-rueda
  url: https://github.com/craig-rueda
name: superset
sources:
- https://github.com/apache/superset
version: 0.14.2
