---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - snapshot.storage.k8s.io_volumesnapshots.yaml
  - groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml
  - groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  - groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
